"""Package SN, spec `handoff/SN-SPEC.md`: `scripts/freeze_message_log.py` freeze/verify/extract.

Fixture: `tests/fixtures/reputation/log-snapshot/messages/{alpha,bravo,charlie}.jsonl` (CRLF, byte-
pinned via `.gitattributes -text`) and the committed expected manifest
`tests/fixtures/reputation/log-snapshot.manifest.json`, generated by freezing that fixture with
`--frozen-at 2026-09-18T00:00:00Z --name log-snapshot --exclude charlie --exclude-reason "test
exclusion"`. `alpha` carries two seq gaps (`[103, 104]`, `[109, 111]`), `bravo` carries one
malformed line and one unsigned row, and a sender posts in both `alpha` and `bravo` -- see
`tests/reputation_fixture_support.py`'s sibling fixtures for the same "generator, not hand-edited"
spirit, though this one lives inline since its whole point is the CRLF byte-exactness a Python
`json.dumps` re-run could not reproduce identically after a `.gitattributes`-less checkout.

Everything here is offline and subprocess-based (same convention as
`tests/test_reputation_build_cli.py`); every subprocess call carries a timeout so a bug here can
never hang the suite, and no path is machine-specific (all come from pytest's `tmp_path`).
"""

import gzip
import io
import json
import os
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "scripts" / "freeze_message_log.py"
FIXTURE_ROOT = REPO / "tests" / "fixtures" / "reputation" / "log-snapshot"
MANIFEST_FIXTURE = REPO / "tests" / "fixtures" / "reputation" / "log-snapshot.manifest.json"
SUBPROCESS_TIMEOUT = 60

FREEZE_ARGS = [
    "freeze",
    "--log-root", str(FIXTURE_ROOT),
    "--name", "log-snapshot",
    "--exclude", "charlie",
    "--exclude-reason", "test exclusion",
    "--frozen-at", "2026-09-18T00:00:00Z",
]


def _run(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        cwd=str(REPO), capture_output=True, text=True, timeout=SUBPROCESS_TIMEOUT,
    )


def _freeze(out_dir: Path) -> subprocess.CompletedProcess[str]:
    proc = _run(*FREEZE_ARGS, "--out-dir", str(out_dir))
    assert proc.returncode == 0, (proc.stdout, proc.stderr)
    return proc


def _committed_manifest() -> dict[str, Any]:
    manifest: dict[str, Any] = json.loads(MANIFEST_FIXTURE.read_text(encoding="utf-8"))
    return manifest


def _crafted_archive(tmp_path: Path, members: list[tuple[str, bytes]]) -> tuple[Path, Path]:
    """A hand-built `.tar.gz` with the given `(name, payload)` members (in that order, duplicates
    allowed) plus a minimal manifest, for the safety-check tests."""
    tar_buffer = io.BytesIO()
    with tarfile.open(fileobj=tar_buffer, mode="w", format=tarfile.GNU_FORMAT) as tar:
        for name, payload in members:
            info = tarfile.TarInfo(name=name)
            info.size = len(payload)
            tar.addfile(info, io.BytesIO(payload))
    gzip_buffer = io.BytesIO()
    with gzip.GzipFile(fileobj=gzip_buffer, mode="wb", mtime=0, filename="") as gz:
        gz.write(tar_buffer.getvalue())
    archive_path = tmp_path / "crafted.tar.gz"
    archive_path.write_bytes(gzip_buffer.getvalue())
    manifest_path = tmp_path / "crafted.manifest.json"
    manifest_path.write_text(json.dumps({"rooms": [], "archive": {}, "totals": {}}), "utf-8")
    return archive_path, manifest_path


# ---------------------------------------------------------------------------------------------
# 1. freeze the fixture -> manifest bytes equal the committed manifest exactly.
# ---------------------------------------------------------------------------------------------


def test_freeze_matches_committed_manifest_exactly(tmp_path: Path) -> None:
    out_dir = tmp_path / "out"
    proc = _freeze(out_dir)
    report = json.loads(proc.stdout.strip())
    assert report["rooms"] == 2
    assert report["rows"] == 26
    assert (out_dir / "log-snapshot.manifest.json").read_bytes() == MANIFEST_FIXTURE.read_bytes()


# ---------------------------------------------------------------------------------------------
# 2. freeze twice into two dirs -> both .tar.gz byte-identical, both manifests byte-identical.
# ---------------------------------------------------------------------------------------------


def test_freeze_is_byte_deterministic(tmp_path: Path) -> None:
    out1, out2 = tmp_path / "one", tmp_path / "two"
    _freeze(out1)
    _freeze(out2)
    assert (
        (out1 / "log-snapshot.tar.gz").read_bytes() == (out2 / "log-snapshot.tar.gz").read_bytes()
    )
    assert (
        (out1 / "log-snapshot.manifest.json").read_bytes()
        == (out2 / "log-snapshot.manifest.json").read_bytes()
    )


# ---------------------------------------------------------------------------------------------
# 3. verify on that output -> ok: true; flip a manifest field -> ok: false, mismatch named.
# ---------------------------------------------------------------------------------------------


def test_verify_ok_then_flags_a_mutated_manifest_field(tmp_path: Path) -> None:
    out_dir = tmp_path / "out"
    _freeze(out_dir)
    archive = out_dir / "log-snapshot.tar.gz"
    manifest = out_dir / "log-snapshot.manifest.json"

    ok_proc = _run("verify", "--archive", str(archive), "--manifest", str(manifest))
    assert ok_proc.returncode == 0, (ok_proc.stdout, ok_proc.stderr)
    ok_report = json.loads(ok_proc.stdout.strip())
    assert ok_report == {
        "ok": True,
        "mismatches": [],
        "rooms": 2,
        "unchecked": ["frozen_at", "name", "excluded", "not_claimed", "layout", "row_schema"],
    }

    mutated = json.loads(manifest.read_text(encoding="utf-8"))
    mutated["rooms"][0]["sha256"] = "0" * 64
    mutated_path = tmp_path / "mutated.manifest.json"
    mutated_path.write_text(json.dumps(mutated), encoding="utf-8")

    bad_proc = _run("verify", "--archive", str(archive), "--manifest", str(mutated_path))
    assert bad_proc.returncode == 1, (bad_proc.stdout, bad_proc.stderr)
    bad_report = json.loads(bad_proc.stdout.strip())
    assert bad_report["ok"] is False
    assert "rooms[0].sha256" in bad_report["mismatches"]


def test_verify_rejects_a_path_traversal_tar_member(tmp_path: Path) -> None:
    archive_path, manifest_path = _crafted_archive(tmp_path, [("../x", b"whatever")])

    proc = _run("verify", "--archive", str(archive_path), "--manifest", str(manifest_path))
    assert proc.returncode == 1, (proc.stdout, proc.stderr)
    report = json.loads(proc.stdout.strip())
    assert report["ok"] is False
    assert any("../x" in m for m in report["mismatches"])


def test_verify_and_extract_refuse_unsafe_member_names(tmp_path: Path) -> None:
    """A backslash cannot be allowed through on Windows (`messages/..\\..\\x.jsonl` would escape
    `--into`), a room named `..` neither, a duplicate member must not silently win, and a member
    outside `messages/<room>.jsonl` is not a snapshot member at all."""
    good = b'{"room": "a", "seq": 1, "ts": "t", "sender": "s", "sig": "x"}\r\n'
    cases: list[tuple[str, list[tuple[str, bytes]]]] = [
        ("backslash", [("messages/..\\..\\x.jsonl", good)]),
        ("dot-dot room", [("messages/...jsonl", good)]),
        ("duplicate member", [("messages/a.jsonl", good), ("messages/a.jsonl", good)]),
        ("not a messages/<room>.jsonl member", [("notes/a.jsonl", good)]),
        ("not a messages/<room>.jsonl member", [("messages/sub/a.jsonl", good)]),
    ]
    for index, (label, members) in enumerate(cases):
        case_dir = tmp_path / f"case-{index}"
        case_dir.mkdir()
        archive_path, manifest_path = _crafted_archive(case_dir, members)

        verify = _run("verify", "--archive", str(archive_path), "--manifest", str(manifest_path))
        assert verify.returncode == 1, (label, verify.stdout, verify.stderr)
        assert json.loads(verify.stdout.strip())["ok"] is False, label

        into = case_dir / "into"
        extract = _run("extract", "--archive", str(archive_path), "--into", str(into))
        assert extract.returncode == 1, (label, extract.stdout, extract.stderr)
        assert not into.exists(), label


# ---------------------------------------------------------------------------------------------
# 4. extract -> byte-equal jsonl, charlie absent; reputation.build matches a manual alpha+bravo
#    copy of the fixture (the snapshot is a faithful ledger input).
# ---------------------------------------------------------------------------------------------


def test_extract_is_byte_equal_and_feeds_reputation_build(tmp_path: Path) -> None:
    out_dir = tmp_path / "out"
    _freeze(out_dir)
    archive = out_dir / "log-snapshot.tar.gz"

    extract_dir = tmp_path / "extracted"
    proc = _run("extract", "--archive", str(archive), "--into", str(extract_dir))
    assert proc.returncode == 0, (proc.stdout, proc.stderr)
    report = json.loads(proc.stdout.strip())
    assert report["extracted"] == 2

    for room in ("alpha", "bravo"):
        assert (extract_dir / "messages" / f"{room}.jsonl").read_bytes() == (
            FIXTURE_ROOT / "messages" / f"{room}.jsonl"
        ).read_bytes()
    assert not (extract_dir / "messages" / "charlie.jsonl").exists()

    manual_root = tmp_path / "manual"
    (manual_root / "messages").mkdir(parents=True)
    for room in ("alpha", "bravo"):
        shutil.copyfile(
            FIXTURE_ROOT / "messages" / f"{room}.jsonl",
            manual_root / "messages" / f"{room}.jsonl",
        )

    env = dict(os.environ)
    env["PYTHONPATH"] = str(REPO / "src")

    extracted_ledger = tmp_path / "extracted-ledger.jsonl"
    manual_ledger = tmp_path / "manual-ledger.jsonl"
    for log_root, out_path in ((extract_dir, extracted_ledger), (manual_root, manual_ledger)):
        build_proc = subprocess.run(
            [
                sys.executable, "-m", "openagentsearch.reputation.build",
                "--log-root", str(log_root), "--out", str(out_path), "--now", "1758000000.0",
            ],
            cwd=str(REPO), env=env, capture_output=True, text=True, timeout=SUBPROCESS_TIMEOUT,
        )
        assert build_proc.returncode == 0, (build_proc.stdout, build_proc.stderr)
        payload = json.loads(build_proc.stdout.strip())
        # The fixture rows must be REAL ledger input (the writer's shape: numeric observed_at,
        # string nonce), otherwise this equality would compare two empty ledgers and prove nothing.
        assert payload["posts"] == 25, payload  # 26 rows minus bravo's one unsigned row
        assert payload["skipped_malformed"] == 1, payload  # bravo's non-JSON line
        assert payload["skipped_unsigned"] == 1, payload
        assert payload["dids"] == 5, payload  # 6 distinct senders minus the unsigned row's

    assert extracted_ledger.read_bytes() == manual_ledger.read_bytes()


def test_truncated_or_corrupted_archive_is_a_clean_exit_2(tmp_path: Path) -> None:
    """A half-finished download (truncated gzip -> `EOFError`) or a corrupted one (`zlib.error`)
    must produce the documented `{"error": ...}` stderr line and exit 2 from both `verify` and
    `extract`, never a traceback -- the lens caught the original `except OSError` missing both."""
    out_dir = tmp_path / "out"
    _freeze(out_dir)
    archive = out_dir / "log-snapshot.tar.gz"
    manifest = out_dir / "log-snapshot.manifest.json"
    raw = archive.read_bytes()

    truncated = tmp_path / "truncated.tar.gz"
    truncated.write_bytes(raw[: len(raw) // 2])
    corrupted = tmp_path / "corrupted.tar.gz"
    corrupted.write_bytes(raw[:20] + bytes(b ^ 0xFF for b in raw[20:60]) + raw[60:])

    for broken in (truncated, corrupted):
        verify = _run("verify", "--archive", str(broken), "--manifest", str(manifest))
        assert verify.returncode == 2, (broken.name, verify.stdout, verify.stderr)
        assert verify.stdout == ""
        assert "Traceback" not in verify.stderr
        assert json.loads(verify.stderr.strip())["error"].startswith("cannot decompress")

        into = tmp_path / f"into-{broken.stem}"
        extract = _run("extract", "--archive", str(broken), "--into", str(into))
        assert extract.returncode == 2, (broken.name, extract.stdout, extract.stderr)
        assert "Traceback" not in extract.stderr
        assert json.loads(extract.stderr.strip())["error"].startswith("cannot read archive")
        assert not into.exists()


def test_extract_refuses_to_overwrite_an_existing_messages_dir(tmp_path: Path) -> None:
    out_dir = tmp_path / "out"
    _freeze(out_dir)
    archive = out_dir / "log-snapshot.tar.gz"

    extract_dir = tmp_path / "extracted"
    (extract_dir / "messages").mkdir(parents=True)
    (extract_dir / "messages" / "sentinel.txt").write_text("keep me", encoding="utf-8")

    proc = _run("extract", "--archive", str(archive), "--into", str(extract_dir))
    assert proc.returncode == 2, (proc.stdout, proc.stderr)
    assert (extract_dir / "messages" / "sentinel.txt").read_text(encoding="utf-8") == "keep me"


# ---------------------------------------------------------------------------------------------
# 5. tar hygiene: fixed TarInfo fields, sorted names, zero gzip mtime.
# ---------------------------------------------------------------------------------------------


def test_tar_hygiene(tmp_path: Path) -> None:
    out_dir = tmp_path / "out"
    _freeze(out_dir)
    archive = out_dir / "log-snapshot.tar.gz"

    raw = archive.read_bytes()
    assert raw[4:8] == b"\x00\x00\x00\x00"

    with tarfile.open(archive, "r:gz") as tar:
        members = tar.getmembers()
        names = [m.name for m in members]
        assert names == ["messages/alpha.jsonl", "messages/bravo.jsonl"]
        assert names == sorted(names)
        for member in members:
            assert member.mtime == 0
            assert member.uid == 0
            assert member.gid == 0
            assert member.uname == ""
            assert member.gname == ""
            assert member.mode == 0o644
            assert member.isreg()


# ---------------------------------------------------------------------------------------------
# 6. errors.
# ---------------------------------------------------------------------------------------------


def test_exclude_nosuch_exits_2(tmp_path: Path) -> None:
    proc = _run(
        "freeze", "--log-root", str(FIXTURE_ROOT), "--out-dir", str(tmp_path / "out"),
        "--name", "x", "--exclude", "nosuch",
    )
    assert proc.returncode == 2, (proc.stdout, proc.stderr)
    assert not (tmp_path / "out").exists()


def test_existing_output_is_refused_and_left_unchanged(tmp_path: Path) -> None:
    out_dir = tmp_path / "out"
    _freeze(out_dir)
    manifest_path = out_dir / "log-snapshot.manifest.json"
    before = manifest_path.read_bytes()

    proc = _run(*FREEZE_ARGS, "--out-dir", str(out_dir))
    assert proc.returncode == 2, (proc.stdout, proc.stderr)
    assert manifest_path.read_bytes() == before


def test_room_and_exclude_together_exits_2(tmp_path: Path) -> None:
    proc = _run(
        "freeze", "--log-root", str(FIXTURE_ROOT), "--out-dir", str(tmp_path / "out"),
        "--name", "x", "--room", "alpha", "--exclude", "bravo",
    )
    assert proc.returncode == 2, (proc.stdout, proc.stderr)
    assert not (tmp_path / "out").exists()


# ---------------------------------------------------------------------------------------------
# 7. manifest sanity on the fixture.
# ---------------------------------------------------------------------------------------------


def test_manifest_sanity_gap_intervals_and_derived_counts() -> None:
    manifest = _committed_manifest()
    rooms = {room["room"]: room for room in manifest["rooms"]}

    alpha = rooms["alpha"]
    assert alpha["gap_intervals"] == [[103, 104], [109, 111]]
    assert alpha["missing_within_range"] == alpha["seq_range"] - alpha["distinct_seq"]

    bravo = rooms["bravo"]
    assert bravo["signed_rows"] == bravo["rows"] - 1

    assert manifest["totals"]["malformed_lines"] == 1
    # the sender shared between alpha and bravo is counted exactly once in the union.
    assert manifest["totals"]["distinct_senders"] == (
        alpha["distinct_senders"] + bravo["distinct_senders"] - 1
    )
